name: RECOVERY.sdibyt

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL (supports MEGA, transfer.sh, oshi.at, etc.)'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

       - name: Prepare environment
      run: |
        sudo apt update
        sudo apt install -y git wget lz4 tar openssl python3 megatools
        # Make magiskboot executable
        chmod +x "$GITHUB_WORKSPACE/magiskboot"
        # Copy into repo root so ./magiskboot works
        cp "$GITHUB_WORKSPACE/magiskboot" "$GITHUB_WORKSPACE/./magiskboot"
        # Also symlink to global PATH
        sudo ln -sf "$GITHUB_WORKSPACE/magiskboot" /usr/local/bin/magiskboot
        echo "Magiskboot path test:"
        ls -l "$GITHUB_WORKSPACE/magiskboot"
        "$GITHUB_WORKSPACE/magiskboot" --help || true
        which magiskboot
        magiskboot --help || true
e

    - name: Fetch recovery image
      run: |
        URL="${{ github.event.inputs.RECOVERY_URL }}"
        echo "Downloading from: $URL"
        if [[ "$URL" == *"mega.nz"* ]]; then
          megadl "$URL" --path RECOVERY.new
        else
          wget -O RECOVERY.new "$URL"
        fi
        cp -f RECOVERY.new recovery.img
        ls -lh recovery.img

    - name: Make scripts executable
      run: |
        chmod +x script1.sh || true
        chmod +x script2.sh || true

    - name: Patch Process-1
      run: ./script1.sh || true

    - name: Patch Process-2
      run: |
        # Ensure script2 uses absolute path if needed
        sed -i "s|magiskboot|/usr/local/bin/magiskboot|g" script2.sh || true
        ./script2.sh || true

        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer \
          --partition_name recovery \
          --partition_size $(wc -c recovery.img | cut -f 1 -d ' ') \
          --image recovery-patched.img \
          --key phh.pem \
          --algorithm SHA256_RSA4096

        mkdir -p output
        mv recovery-patched.img output/recovery.img
        cd output
        tar cvf fastbootd-recovery.tar recovery.img
        md5sum fastbootd-recovery.tar > fastbootd-recovery.tar.md5

    - name: Upload Patched Recovery
      uses: actions/upload-artifact@v4
      with:
        name: Patched-Recovery
        path: output/*
