name: RECOVERY.goon

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL (supports MEGA, Transfer.sh, Oshi.at, etc.)'
        required: true
        default: 'https://transfer.sh/(RECOMMENDED)'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt install git wget lz4 tar openssl python3 -y
        pip install mega.py
        chmod +x $GITHUB_WORKSPACE/magiskboot
        echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH

    - name: Fetch recovery image
      run: |
        URL="${{ github.event.inputs.RECOVERY_URL }}"
        if [[ "$URL" == *"mega.nz"* ]]; then
          echo "Downloading from MEGA..."
          python3 - <<'EOF'
from mega import Mega
m = Mega()
m.download_url("${{ github.event.inputs.RECOVERY_URL }}", 'RECOVERY.new')
EOF
        else
          echo "Downloading via wget..."
          wget "$URL" -O RECOVERY.new
        fi
        ls -lh RECOVERY.new

    - name: Patch Process-1
      run: |
        chmod +x script1.sh
        ./script1.sh || true

    - name: Patch Process-2
      run: |
        chmod +x script2.sh
        sed -i "s|magiskboot|$GITHUB_WORKSPACE/magiskboot|g" script2.sh
        ./script2.sh || true

        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer \
          --partition_name recovery \
          --partition_size $(wc -c RECOVERY.new | cut -f 1 -d ' ') \
          --image recovery-patched.img \
          --key phh.pem \
          --algorithm SHA256_RSA4096

        mkdir output && cd output
        mv ../recovery-patched.img recovery.img
        tar cvf fastbootd-recovery.tar recovery.img
        md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
        mv fastbootd-recovery.tar fastbootd-recovery.tar.md5

    - name: Upload Recovery
      uses: actions/upload-artifact@v4
      with:
        path: output/*.md5
        name: Patched-Recovery
