name: RECOVERY.new

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true
        default: 'https://mega.nz/file/xxxx#yyyy'

env:
  RECOVERY_URL: https://mega.nz/file/yTQVkJAR#s30tgTgqP4FckygbuLi8xWaBLJTym6ddJIrkb8Z_kvI

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt install -y git wget lz4 tar openssl python3 megatools

    - name: Fetch image from MEGA
      run: |
        ls
        pwd
        megadl "${{ github.event.inputs.RECOVERY_URL }}" --path recovery.img

    - name: Patch Process-1
      run: |
        chmod +x magiskboot
        chmod +x script1.sh
        ./script1.sh || true

    - name: Patch Process-2
      run: |
        chmod +x magiskboot
        chmod +x script2.sh
        ./script2.sh || true
        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img | cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
        mkdir output && cd output
        mv ../recovery-patched.img recovery.img
        tar cvf fastbootd-recovery.tar recovery.img
        md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
        mv fastbootd-recovery.tar fastbootd-recovery.tar.md5

    - name: Upload Recovery
      uses: actions/upload-artifact@v4.0.0
      with:
        path: /home/runner/work/Patch-Recovery/Patch-Recovery/output/*.md5
        name: Patched-Recovery
