name: RECOVERY.josdfiofnonfiniofn

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true
        default: 'https://oshi.at/(RECOMMENDED)'

env:
  RECOVERY_URL: https://oshi.at/Rpjg

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare environment
      run: |
        sudo apt update
        sudo apt install -y git wget lz4 tar openssl python3 megatools
        chmod +x "$GITHUB_WORKSPACE/magiskboot"
        # Copy into repo root so ./magiskboot works
        cp "$GITHUB_WORKSPACE/magiskboot" "$GITHUB_WORKSPACE/./magiskboot"
        # Also symlink to global PATH
        sudo ln -sf "$GITHUB_WORKSPACE/magiskboot" /usr/local/bin/magiskboot
        echo "Magiskboot path test:"
        ls -l "$GITHUB_WORKSPACE/magiskboot"
        "$GITHUB_WORKSPACE/magiskboot" --help || true
        which magiskboot
        magiskboot --help || true

    - name: Fetch image from URL
      run: |
        echo "Downloading recovery from: ${{ github.event.inputs.RECOVERY_URL }}"
        if [[ "${{ github.event.inputs.RECOVERY_URL }}" == *"mega.nz"* ]]; then
          megadl "${{ github.event.inputs.RECOVERY_URL }}" --path recovery.img
        else
          wget "${{ github.event.inputs.RECOVERY_URL }}" -O recovery.img
        fi
        ls -lh recovery.img

    - name: Patch Process-1
      run: |
        chmod a+x script1.sh
        ./script1.sh || true

    - name: Patch Process-2
      run: |
        chmod a+x script2.sh
        echo "=== First 20 lines of script2.sh ==="
        head -n 20 script2.sh
        ./script2.sh || true
        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer \
          --partition_name recovery \
          --partition_size $(wc -c recovery.img |cut -f 1 -d ' ') \
          --image recovery-patched.img \
          --key phh.pem --algorithm SHA256_RSA4096
        mkdir output && cd output
        mv ../recovery-patched.img recovery.img
        tar cvf fastbootd-recovery.tar recovery.img
        md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
        mv fastbootd-recovery.tar fastbootd-recovery.tar.md5

    - name: Upload Recovery
      uses: actions/upload-artifact@v4.0.0
      with:
        path: /home/runner/work/Patch-Recovery/Patch-Recovery/output/*.md5
        name: Patched-Recovery
