name: RECOVERY.new

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'Recovery image URL (Mega/Transfer.sh/Oshi.at/etc)'
        required: true
        default: 'https://mega.nz/file/xxxx#yyyy'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        sudo apt update
        sudo apt install -y git wget lz4 tar openssl python3 megatools
        chmod +x "$GITHUB_WORKSPACE/magiskboot"
        sudo ln -sf "$GITHUB_WORKSPACE/magiskboot" /usr/local/bin/magiskboot
        which magiskboot
        magiskboot --help || true

    - name: Fetch image from URL
      run: |
        URL="${{ github.event.inputs.RECOVERY_URL }}"
        if [[ "$URL" == *"mega.nz"* ]]; then
          echo "Downloading from Mega..."
          megadl "$URL" --path recovery.img
        else
          echo "Downloading via wget..."
          wget "$URL" -O recovery.img
        fi
        if [ ! -f recovery.img ]; then
          echo "No recovery.img downloaded!"
          exit 1
        fi
        mv recovery.img RECOVERY.new || true
        cp RECOVERY.new recovery.img || true
        ls -lh

    - name: Patch Process-1
      run: |
        chmod +x script1.sh
        ./script1.sh || true

    - name: Patch Process-2
      run: |
        chmod +x script2.sh
        ./script2.sh || true
        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer \
          --partition_name recovery \
          --partition_size $(wc -c recovery.img |cut -f 1 -d ' ') \
          --image recovery-patched.img \
          --key phh.pem \
          --algorithm SHA256_RSA4096
        mkdir output
        mv recovery-patched.img output/recovery.img
        cd output
        tar cvf fastbootd-recovery.tar recovery.img
        md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
        mv fastbootd-recovery.tar fastbootd-recovery.tar.md5

    - name: Upload Recovery
      uses: actions/upload-artifact@v4
      with:
        path: output/*.md5
        name: Patched-Recovery
